# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-08 23:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20171008_1916'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': (('create_orders', 'Can create new orders'),)},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(default='unpaid', max_length=20),
        ),
    ]
