# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-09 01:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20171008_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdish',
            old_name='dish_price',
            new_name='fact_price',
        ),
    ]
