# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-10-10 22:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20171009_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('DUE', 'Unpaid'), ('OK', 'Paid'), ('CANCELLED', 'Cancelled')], default='DUE', max_length=20),
        ),
    ]
